### ISSUE TITLE
ServiceBackedAudioPlayer: NPE getCurrentPosition()

### ISSUE THREAD

**Issue by mfietz** [AntennaPod/AntennaPod-AudioPlayer#1]
```
java.lang.NullPointerException: Attempt to invoke interface method 'int com.aocate.presto.service.IPlayMedia_0_8.getCurrentPosition(long)' on a null object reference
	at org.antennapod.audio.ServiceBackedAudioPlayer.getCurrentPosition(ServiceBackedAudioPlayer.java:288)
	at org.antennapod.audio.MediaPlayer.switchMediaPlayerImpl(MediaPlayer.java:541)
	at org.antennapod.audio.MediaPlayer.access$100(MediaPlayer.java:35)
	at org.antennapod.audio.MediaPlayer$4$2.handleMessage(MediaPlayer.java:423)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6117)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by mfietz** [comment]
Resolved by 9b9397ce678cfb48a1593f5d1390533f65e06097
