### ISSUE TITLE
IllegalStateEyxception: Audio Track pointer for start()

### ISSUE THREAD

**Issue by PaulWoitaschek** [AntennaPod/AntennaPod-AudioPlayer#4]
> Caused by: java.lang.IllegalStateException: Unable to retrieve AudioTrack pointer for start()
at android.media.AudioTrack.native_start(Native Method)
at android.media.AudioTrack.play(AudioTrack.java:1147)
at org.antennapod.audio.SonicAudioPlayer.start(SonicAudioPlayer.java:294)
at org.antennapod.audio.MediaPlayer.start(MediaPlayer.java:1269)
at de.ph1b.audiobook.playback.AntennaPlayerDelegate.start(AntennaPlayerDelegate.kt:55)

Full report: [ACRA](http://acra-63e870.smileupps.com/acralyzer/_design/acralyzer/index.html#/reports-browser/material/bug/36e759ca2c3e01208da09f432959c9ad)

Is it okay for you if I report bugs like this? There is not much more details I have on this.

**Comment by mfietz** [comment]
The stack trace should be enough in most cases.

**Comment by PaulWoitaschek** [comment]
Still present in 1.11

**Comment by mfietz** [comment]
What do I have to do to cause this issue?

**Comment by mfietz** [comment]
Palim, Palim

**Comment by PaulWoitaschek** [comment]
I don't know. It is a crashreport that was reported to me.
