### ISSUE TITLE
Invalid channel configuration

### ISSUE THREAD

**Issue by mfietz** [AntennaPod/AntennaPod-AudioPlayer#6]
```
E/android.media.AudioTrack(17537): getMinBufferSize(): Invalid channel configuration.
E/android.media.AudioTrack(17537): Channel configuration features unsupported channels
E/SonicAudioPlayer(17537): java.lang.IllegalArgumentException: Unsupported channel configuration.
E/SonicAudioPlayer(17537):  at android.media.AudioTrack.audioParamCheck(AudioTrack.java:512)
E/SonicAudioPlayer(17537):  at android.media.AudioTrack.<init>(AudioTrack.java:428)
E/SonicAudioPlayer(17537):  at android.media.AudioTrack.<init>(AudioTrack.java:359)
E/SonicAudioPlayer(17537):  at android.media.AudioTrack.<init>(AudioTrack.java:316)
E/SonicAudioPlayer(17537):  at org.antennapod.audio.SonicAudioPlayer.createAudioTrack(SonicAudioPlayer.java:579)
E/SonicAudioPlayer(17537):  at org.antennapod.audio.SonicAudioPlayer.initDevice(SonicAudioPlayer.java:565)
E/SonicAudioPlayer(17537):  at org.antennapod.audio.SonicAudioPlayer.initStream(SonicAudioPlayer.java:546)
E/SonicAudioPlayer(17537):  at org.antennapod.audio.SonicAudioPlayer.prepare(SonicAudioPlayer.java:208)
E/SonicAudioPlayer(17537):  at org.antennapod.audio.MediaPlayer.prepare(MediaPlayer.java:871)
E/SonicAudioPlayer(17537):  at de.danoeh.antennapod.core.service.playback.PlaybackServiceMediaPlayer.playMediaObject(PlaybackServiceMediaPlayer.java:268)
E/SonicAudioPlayer(17537):  at de.danoeh.antennapod.core.service.playback.PlaybackServiceMediaPlayer.access$100(PlaybackServiceMediaPlayer.java:53)
E/SonicAudioPlayer(17537):  at de.danoeh.antennapod.core.service.playback.PlaybackServiceMediaPlayer$2.run(PlaybackServiceMediaPlayer.java:183)
E/SonicAudioPlayer(17537):  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
E/SonicAudioPlayer(17537):  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/SonicAudioPlayer(17537):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/SonicAudioPlayer(17537):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/SonicAudioPlayer(17537):  at java.lang.Thread.run(Thread.java:818)
W/System.err(17537): java.lang.IllegalStateException: Could not create buffer for AudioTrack
W/System.err(17537):    at org.antennapod.audio.SonicAudioPlayer.createAudioTrack(SonicAudioPlayer.java:595)
W/System.err(17537):    at org.antennapod.audio.SonicAudioPlayer.initDevice(SonicAudioPlayer.java:565)
W/System.err(17537):    at org.antennapod.audio.SonicAudioPlayer.initStream(SonicAudioPlayer.java:546)
W/System.err(17537):    at org.antennapod.audio.SonicAudioPlayer.prepare(SonicAudioPlayer.java:208)
W/System.err(17537):    at org.antennapod.audio.MediaPlayer.prepare(MediaPlayer.java:871)
W/System.err(17537):    at de.danoeh.antennapod.core.service.playback.PlaybackServiceMediaPlayer.playMediaObject(PlaybackServiceMediaPlayer.java:268)
W/System.err(17537):    at de.danoeh.antennapod.core.service.playback.PlaybackServiceMediaPlayer.access$100(PlaybackServiceMediaPlayer.java:53)
W/System.err(17537):    at de.danoeh.antennapod.core.service.playback.PlaybackServiceMediaPlayer$2.run(PlaybackServiceMediaPlayer.java:183)
W/System.err(17537):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/System.err(17537):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err(17537):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err(17537):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err(17537):    at java.lang.Thread.run(Thread.java:818)
```

**Comment by mfietz** [comment]
Resolved by afb7e7c64f5d79f4a516bd975bb98f9bc5c8617e
